### ISSUE TITLE
Allow multiple managers

### ISSUE THREAD

**Issue by DanielW48** [ucf-tower-app/web#68]
previously our promoting manager method was to handoff the 'single torch' of manager role to someone else. However upon further consideration, we gotta fix that. There will be at least two people that have the manager role at the Tower at the same time (Tower Lead and Head Setter), but there are probably more people that we want to have the ability to have this as well (perhaps some Outdoor Adventure higher-ups will want manager permissions in the app)

**Comment by Henry-Graves** [comment]
duplicate issue, see #87
