### ISSUE TITLE
Allow Managers to Promote Employees to Managers

### ISSUE THREAD

**Issue by DanielW48** [ucf-tower-app/web#87]
We originally had the idea of having only 1 manager at any time, but this will be problematic if multiple Tower higher-ups need manager permissions (Tower Lead, Head Setter, and likely a few more employees will need manager permissions). This means that we will allow MANAGERS to promote EMPLOYEES to MANAGER.

Code Pointer is here: https://github.com/ucf-tower-app/web/blob/815a66fb0076f0fe0df394061e59c71898e08082/src/components/Profile/ProfileBanner.tsx#L22

We need to rename the managerSwap function, and check it to make sure the current logged in user is a MANAGER, the user being viewed is an EMPLOYEE, and then execute the promotion through API.

**Comment by Henry-Graves** [comment]
backend for allowing multiple managers is done but waiting on a PR: https://github.com/ucf-tower-app/xplat/pull/248

gonna take a look at the frontend for this today
